// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKpCwMEa6JiWM7WSOZ35nbpZ_HXYH_TjI',
    appId: '1:442655152265:web:d4041a7c8efdcac08fce58',
    messagingSenderId: '442655152265',
    projectId: 'shop_villa-f3d48',
    authDomain: 'shop_villa-f3d48.firebaseapp.com',
    storageBucket: 'shop_villa-f3d48.appspot.com',
    measurementId: 'G-BDE8FEL31V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWil-8Lh4S_Ww_1iXSTOVcl4k241JdXg',
    appId: '1:442655152265:android:703c8fc8fd871ec68fce58',
    messagingSenderId: '442655152265',
    projectId: 'shop_villa-f3d48',
    storageBucket: 'shop_villa-f3d48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZiS_GkBXiHATD8E2uddAMtrRfNFYg8w',
    appId: '1:442655152265:ios:56dd561283adfccb8fce58',
    messagingSenderId: '442655152265',
    projectId: 'shop_villa-f3d48',
    storageBucket: 'shop_villa-f3d48.appspot.com',
    iosBundleId: 'com.arcadexit.com.shop_villa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ZiS_GkBXiHATD8E2uddAMtrRfNFYg8w',
    appId: '1:442655152265:ios:56dd561283adfccb8fce58',
    messagingSenderId: '442655152265',
    projectId: 'shop_villa-f3d48',
    storageBucket: 'shop_villa-f3d48.appspot.com',
    iosBundleId: 'com.arcadexit.com.shop_villa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKpCwMEa6JiWM7WSOZ35nbpZ_HXYH_TjI',
    appId: '1:442655152265:web:d13bf172d2f335048fce58',
    messagingSenderId: '442655152265',
    projectId: 'shop_villa-f3d48',
    authDomain: 'shop_villa-f3d48.firebaseapp.com',
    storageBucket: 'shop_villa-f3d48.appspot.com',
    measurementId: 'G-GXRTJ8JRJR',
  );
}
